FROM nvidia/cuda:12.2.0-cudnn8-runtime-ubuntu22.04

WORKDIR /workspace

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y python3 python3-pip git

# Copia los archivos del proyecto
COPY . .

# Instala dependencias de Python
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# Variable de entorno para TensorFlow y CUDA
ENV TF_CPP_MIN_LOG_LEVEL=2

CMD ["python3", "run_con_per.py"]