# Usamos una imagen base de Python con soporte para GPU
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Instalamos Python y pip
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el archivo de requisitos
COPY requirements.txt .

# Instalamos las dependencias
RUN pip3 install --no-cache-dir -r requirements.txt

# Copiamos todo el contenido del proyecto
COPY . .

# Expone el puerto si es necesario
EXPOSE 8888

# Comando para ejecutar el script de Python
CMD ["python3", "run_con_per.py"]
